language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# so Selenium can run
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
#script: "python selenium-crawler/run_tests.py"
script:
  - "strace -q python selenium-crawler/run_tests.py 2>&1 | grep -v ENOENT"
